function togglePost(t){let e=JSON.parse(localStorage.getItem("bookmarkedPosts"))||[],o=e.indexOf(t);-1===o?e.push(t):e.splice(o,1),localStorage.setItem("bookmarkedPosts",JSON.stringify(e)),updateSaveButtons(t),updateBookmarkCount()}function updateSaveButtons(t){let e=document.querySelectorAll(`.saveBtn[data-postId='${t}']`),o=JSON.parse(localStorage.getItem("bookmarkedPosts"))||[],s=o.includes(t);e.forEach(t=>{s?t.classList.add("saved"):t.classList.remove("saved")})}function loadSavedPosts(){let t=JSON.parse(localStorage.getItem("bookmarkedPosts"))||[];t.forEach(t=>updateSaveButtons(t)),updateBookmarkCount()}function updateBookmarkCount(){let t=JSON.parse(localStorage.getItem("bookmarkedPosts"))||[],e=document.getElementById("post-count");e.setAttribute("data-text",t.length)}document.querySelectorAll(".saveBtn").forEach(t=>{t.addEventListener("click",()=>{let e=t.getAttribute("data-postId");togglePost(e)})}),loadSavedPosts();
async function loadBookmarkedPosts(){let e=document.getElementById("postContainer"),t=JSON.parse(localStorage.getItem("bookmarkedPosts"))||[],a=t.map(e=>{let t=`/feeds/posts/default/${e}?alt=json`;return fetch(t).then(e=>e.json())}),s=await Promise.all(a),l=s.filter(e=>null!==e);0===l.length?e.innerHTML="<p>No posts found.</p>":renderPosts(l)}function renderPosts(e){let t=document.getElementById("postContainer");t.innerHTML="",e.forEach(e=>{let a=e.entry,s=a.title.$t,l=a.link.find(e=>"alternate"===e.rel).href;imgSrc=a.media$thumbnail?a.media$thumbnail.url.replace(/\/s\d+\-c\//,"/s300-c/"):"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj7gSvkTm6-PuGZ2ni5DCI8oGcunBYrCBSvAJvZ0s881WWOmbP2F2T2j9gYpEDpiGNqipehIA46Eb0WEZqYwC8nH3LEz6zQPNnzcS9vGkaMFZq21Y8kGPvQhsI4qWxjvqKL5b-fSjVmD8P9GJli-aOyv4b9rYPCrjWsH1NFrZN8K8U_ett_MFiSBhkaemAW/s1600/noImage.png";let n=a.category?a.category.map(e=>e.term):[];n.length>0&&n[0];let o=document.createElement("article");o.classList.add("bookmark-post"),o.innerHTML=`
<div class='img shrink'>
<a href="${l}" aria-label="Thumbnail">
<img src="${imgSrc}" loading="lazy" alt="${s}">
</a>
</div>
<div class="bTitle cInherit">
<h2 class="name">
<a class="clamp" href="${l}">${s}</a>
</h2>
</div>
<div class="deleteBtn flex center shrink i18" data-postId="${a.id.$t.split(".post-").pop()}"><svg class="line" viewBox="0 0 24 24"><path d="M 18.645 9.251 L 18.649 12.575 M 17.667 19.142 L 15.545 17.021 M 15.544 21.263 L 17.667 19.142 M 19.788 17.021 L 17.667 19.142 M 17.666 19.142 L 19.787 21.263 M 8.625 5.217 L 15.375 5.217 M 4.212 5.217 L 8.821 5.217 M 19.788 5.217 L 15.179 5.217 M 8.625 5.203 L 8.625 4.19 C 8.625 3.085 9.52 2.19 10.625 2.19 L 13.375 2.19 C 14.479 2.19 15.375 3.085 15.375 4.19 L 15.375 5.203 M 10.844 21.263 L 7.53 21.263 C 6.454 21.263 5.532 20.618 5.346 19.735 L 5.355 9.251"></path></svg></div>
`,t.appendChild(o),o.querySelector(".deleteBtn").addEventListener("click",e=>{let t=e.target.getAttribute("data-postId");deletePost(t)})})}function deletePost(e){let t=JSON.parse(localStorage.getItem("bookmarkedPosts"))||[];t=t.filter(t=>t!==e),localStorage.setItem("bookmarkedPosts",JSON.stringify(t));let a=document.querySelector(`.deleteBtn[data-postId='${e}']`).closest(".bookmark-post");a&&a.remove(),updateBookmarkCount();let s=document.getElementById("postContainer");if(0===t.length){s.innerHTML="<p>No bookmarks yet.</p>";return}}null!==document.querySelector("#postContainer")&&loadBookmarkedPosts();
