const feedUrl="/feeds/posts/default?alt=json",maxPosts=5;let currentSlide=0,posts=[],slideInterval;async function fetchFeed(){try{let e=await fetch("/feeds/posts/default?alt=json"),t=await e.json(),i=t.feed.entry;posts=getUniqueRandomPosts(i,5),createSlider(posts),sliderContainer.classList.remove("hidden")}catch(l){console.error("Error fetching feed:",l)}}function getUniqueRandomPosts(e,t){let i=[],l=new Set;for(;i.length<t&&l.size<e.length;){let n=Math.floor(Math.random()*e.length);l.has(n)||(l.add(n),i.push(e[n]))}return i}function createSlider(e){let t=document.getElementById("posts-container"),i=document.getElementById("sliderPoints");e.forEach((e,l)=>{let n=document.createElement("article");n.classList.add("slide"),0===l&&n.classList.add("active");let a=e.media$thumbnail?e.media$thumbnail.url:null,s=e.link.find(e=>"alternate"===e.rel).href,r=a?a.replace("/s72-c/","/w1600-h900-c/"):"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjEa-Z91T3IRbKpQtTj0z5QKZY31lpXagnxJASMnXo82v0kJhBZim2Xc_8qg8ns5libjP-_0l0ZH3XYo2Fqpz1n1Ja6sAUk_VRaN9-YPTvPeFn4Cq1stbc7MugAceaze7bqzWHNlnDdmqmi-woRLsLxGUaTqemOMiSELIV1Q5ybDPcQ5IaQ-wQjaDnfbo2w/s1600/noImage.jpg",d=e.title.$t,o=e.category[0]?.term||"Uncategorized",c=formatDateTime(e.published.$t),u=e.updated?formatDateTime(e.updated.$t):c;n.innerHTML=`
<div class="slide-thmb cInherit">
<a class="notH" href="${s}">
<img src="${r}" alt="${d}" loading='lazy'></a>
<div class='infoa pT'>
<div class="pH info flex fontM">
<time class="time ellips opacity shrink" data-format="short" datetime="${u}">---</time>
<div class="label ellips cInherit"><a href="/search/label/${o}">${o}</a></div>
</div>
<h2 class="name"><a href="${s}">${d}</a></h2>        
</div>
</a>
`,t.appendChild(n);let v=document.createElement("span");0===l&&v.classList.add("active-point"),v.addEventListener("click",()=>goToSlide(l)),i.appendChild(v)}),startAutoSlide()}function formatDateTime(e){let t=new Date(e);return t.toISOString()}function changeSlide(e){let t=document.querySelectorAll(".slide"),i=document.querySelectorAll(".slider-points span");t[currentSlide].classList.remove("active"),i[currentSlide].classList.remove("active-point"),t[currentSlide=(currentSlide+e+t.length)%t.length].classList.add("active"),i[currentSlide].classList.add("active-point")}function goToSlide(e){let t=document.querySelectorAll(".slide"),i=document.querySelectorAll(".slider-points span");t[currentSlide].classList.remove("active"),i[currentSlide].classList.remove("active-point"),t[currentSlide=e].classList.add("active"),i[currentSlide].classList.add("active-point"),restartAutoSlide()}function startAutoSlide(){slideInterval=setInterval(()=>{changeSlide(1)},2500)}function restartAutoSlide(){clearInterval(slideInterval),startAutoSlide()}document.getElementById("prevBtn").addEventListener("click",()=>{changeSlide(-1),restartAutoSlide()}),document.getElementById("nextBtn").addEventListener("click",()=>{changeSlide(1),restartAutoSlide()});const sliderContainer=document.getElementById("sliderContainer"),events=["mouseenter","touchstart","mouseover"],clearSlideInterval=()=>clearInterval(slideInterval),restartSlideInterval=()=>restartAutoSlide();events.forEach(e=>sliderContainer.addEventListener(e,clearSlideInterval,{passive:!0})),["mouseleave","touchend","mouseout"].forEach(e=>sliderContainer.addEventListener(e,restartSlideInterval,{passive:!0}));fetchFeed();
